name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          java-version: 8
          
      - name: Build and check
        run: ./gradlew assembleDebug assembleDebugAndroidTest app:lintDebug testDebug --scan
